{
    "name": "MRP Batch",
    "version": "17.0.0.0.0",
    "license": "AGPL-3",
    "description": "Package management for mrp production batch",
    "author": "Open Source Integrators",
    "maintainer": "Open Source Integrators",
    "website": "http://www.opensourceintegrators.com",
    "category": "",
    "images": [],
    "depends": [
        "mrp",
        "mrp_workorder",
        "mrp_exception",
        "sale_management",
        "sale_mrp",
        "queue_job",
        "stock_picking_batch",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/mrp_batch_security.xml",
        "data/ir_action_server.xml",
        "data/ir_sequence.xml",
        "data/mrp_exception_data.xml",
        "data/mrp_production_batch_tag_data.xml",
        "data/workcenter_data.xml",
        "data/ir_config_parameter.xml",
        "data/ir_cron.xml",
        "wizard/mrp_production_add_to_existing_batch_wizard.xml",
        "wizard/mrp_production_batch_wizard_view.xml",
        "report/report_view.xml",
        "report/mrp_batch_report_view.xml",
        "views/mrp_production_batch_tag_view.xml",
        "views/mrp_production_batch_view.xml",
        "views/mrp_production_batch_schedule_view.xml",
        "views/mrp_production_view.xml",
        "views/mrp_routing_workcenter.xml",
        "views/mrp_workcenter.xml",
        "views/sale_order_view.xml",
        "views/product_template_view.xml",
        "views/mrp_workorder_view.xml",
        "views/res_config_settings_views.xml",
        "views/stock_picking_views.xml",
    ],
    "auto_install": False,
    "application": False,
    "installable": True,
}
