{
    "name": "Onlogic RMA Supplier",
    "version": "17.0.0.0.0",
    "license": "AGPL-3",
    "description": "Manage Vendor RMA's",
    "author": "Open Source Integrators",
    "maintainer": "Open Source Integrators",
    "website": "http://www.opensourceintegrators.com",
    "category": "",
    "images": [],
    "depends": [
        "stock",
        "delivery",
    ],
    "data": [
        "data/rma_sequence.xml",
        "data/stock_data.xml",
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/res_partner.xml",
        "views/rma_supplier_tag_views.xml",
        "views/rma_supplier_line_views.xml",
        "views/rma_supplier_views.xml",
        "views/stock_picking.xml",
        "views/stock_warehouse.xml",
    ],
    "auto_install": False,
    "application": False,
    "installable": True,
}
