# pylint: disable=pointless-statement
{
    "name": "OnLogic Webhooks",
    "summary": "Adds the possibility to create webhooks that can be called on predefined events.",
    "version": "1.0",
    "depends": [
        "ol_base",
        "ol_api",
        "ol_queue_job",
    ],
    "author": "OnLogic",
    "website": "https://www.onlogic.com",
    "onlogic": True,
    "category": "Tools",
    "description": """Adds the possibility to create webhooks that can be called on predefined events.""",
    "data": [
        "data/api_clients.xml",
        "data/invoice.xml",
        "data/ir_config_parameter.xml",
        "data/ir_cron.xml",
        "data/mrp_production.xml",
        "data/partner.xml",
        "data/product.xml",
        "data/project_task.xml",
        "data/queue_job_channel.xml",
        "data/sale_order.xml",
        "data/stock_picking.xml",
        "security/ir.model.access.csv",
        "views/api_clients.xml",
        "views/webhooks.xml",
        "views/webhooks_events.xml",
        "views/res_config_settings_views.xml",
        "views/product_template.xml",
    ],
}
