{
    "name": "OnLogic Stock customization",
    "summary": "Stock modules related customization",
    "description": """Stock modules related customization.""",
    "author": "OnLogic",
    "website": "https://www.onlogic.com",
    "onlogic": True,
    "category": "stock",
    "version": "17.0.1.0.0",
    "license": "AGPL-3",
    # any module necessary for this one to work correctly
    "depends": [
        "ol_base",
        "ol_templates",
        "ol_stock_loadcsv",
        "ol_rush_order",
        "ol_sale",
        "stock",
        "delivery_stock_picking_batch",
        "purchase_stock",
        "stock_inventory",
    ],
    # always loaded
    "data": [
        "data/stock_location_data.xml",
        "security/security_group.xml",
        "security/ir.model.access.csv",
        "views/stock_picking_type_views.xml",
        "views/stock_picking_view.xml",
        "views/stock_scrap_view.xml",
        "reports/inventory_label.xml",
        "reports/inventory_sheets.xml",
        "reports/packing_slip_from_so.xml",
        "reports/packing_slip.xml",
        "reports/picking_list_from_so.xml",
        "reports/picking_list.xml",
        "wizard/stock_scrap_confirm_wizard_view.xml",
    ],
}
