from odoo import fields, models


class SaleOrder(models.Model):
    _inherit = "sale.order"

    mrp_batch_count = fields.Integer(
        string="mrp batch count",
        compute="_compute_mrp_production_batch_id_count",
    )

    def action_confirm(self):
        res = super().action_confirm()
        self.with_delay().split_mo()
        return res

    def split_mo(self):
        batch_obj = self.env["mrp.production.batch"]
        for rec in self:
            vals = {
                "responsible_id": rec.env.user.id,
            }
            for mo in rec.mrp_production_ids:
                if (
                    mo.product_id.tracking == "serial"
                    and mo.product_id.is_allowe_split_mo
                ):
                    qty = mo.product_qty
                    if qty > 1:
                        mo.sudo()._split_productions({mo: ([1] * int(qty))})[:-1]
            mrp_batch_id = batch_obj.create(vals)
            rec.mrp_production_ids.write({"mrp_batch_id": mrp_batch_id.id})

    def _compute_mrp_production_batch_id_count(self):
        for record in self:
            batch_id = [batch.id for batch in record.mrp_production_ids.mrp_batch_id]
            record.mrp_batch_count = len(batch_id)

    def action_view_mrp_production_batch(self):
        self.ensure_one()
        action = {
            "res_model": "mrp.production.batch",
            "type": "ir.actions.act_window",
        }
        if len([batch.id for batch in self.mrp_production_ids.mrp_batch_id]) == 1:
            action.update(
                {
                    "view_mode": "form",
                    "res_id": self.mrp_production_ids.mrp_batch_id.id,
                }
            )
        else:
            action.update(
                {
                    "name": _(
                        "Manufacturing Production Batch Generated by %s", self.name
                    ),
                    "domain": [("id", "in", self.mrp_production_ids.mrp_batch_id.ids)],
                    "view_mode": "tree,form",
                }
            )
        return action
