# Import Odoo libs
from odoo import fields, models, _


class SaleOrder(models.Model):
    _inherit = "sale.order"

    # COLUMNS #########

    mrp_batch_count = fields.Integer(
        string="mrp batch count",
        compute="_compute_mrp_production_batch_id_count",
    )
    is_mrp_warning = fields.Boolean(compute="_compute_is_mrp_warning")

    # END #########
    # METHODS #####

    def write(self, vals):
        res = super().write(vals)
        if vals.get("order_line", False):
            self.with_delay().split_mo()
        return res

    def _compute_is_mrp_warning(self):
        for so in self:
            is_mrp_warning = False

            # Check if there are any related manufacturing orders (mrp_production_ids)
            # and if any of those orders are planned or in specific states
            if so.mrp_production_ids and so.mrp_production_ids.filtered(
                lambda l: l.is_planned or l.state in ("progress", "to_close", "done")
            ):
                is_mrp_warning = True

            so.is_mrp_warning = is_mrp_warning

    def split_mo(self):
        # Initializes the MRP Production Batch model.
        batch_obj = self.env["mrp.production.batch"]
        for rec in self:
            # Iterates over each manufacturing order in `mrp_production_ids`.
            for mo in rec.mrp_production_ids:
                # Checks if the product requires serial tracking and is
                # allowed to split MOs.
                if (
                    mo.product_id.tracking == "serial"
                    and mo.product_id.is_allow_split_mo
                ):
                    qty = mo.product_qty
                    # If the quantity is greater than 1, splits the MO into units
                    # of 1 and removes the original MO entry by slicing off the
                    # last item.
                    if qty > 1:
                        mo.sudo()._split_productions({mo: ([1] * int(qty))})[:-1]

                    # Check if the current MO already has an assigned batch
                    if not mo.mrp_batch_id:
                        # If no batch exists, create a new batch
                        vals = {
                            "responsible_id": rec.env.user.id,
                        }
                        mrp_batch_id = batch_obj.create(vals)
                        mo.write({"mrp_batch_id": mrp_batch_id.id})
                        mo.backorder_ids.write({"mrp_batch_id": mrp_batch_id.id})
                    else:
                        # If a batch is already set, assign the same batch to the new MOs
                        mo.write({"mrp_batch_id": mo.mrp_batch_id.id})
                        mo.backorder_ids.write({"mrp_batch_id": mo.mrp_batch_id.id})

    # Methods for Batch Smart Button
    def _compute_mrp_production_batch_id_count(self):
        # Computes the count of unique batch IDs linked to the
        # MOs in `mrp_production_ids`.
        for record in self:
            # Collects batch IDs for each MO in `mrp_production_ids`.
            batch_id = [batch.id for batch in record.mrp_production_ids.mrp_batch_id]
            # Sets `mrp_batch_count` to the number of unique batches found.
            record.mrp_batch_count = len(batch_id)

    def action_view_mrp_production_batch(self):
        # Ensures the method is called on a single record.
        self.ensure_one()
        # Defines the base action for viewing the manufacturing production batch.
        action = {
            "res_model": "mrp.production.batch",
            "type": "ir.actions.act_window",
        }
        # Checks if there is only one batch ID in `mrp_production_ids`.
        if len([batch.id for batch in self.mrp_production_ids.mrp_batch_id]) == 1:
            # If there is a single batch, open it in form view.
            action.update(
                {
                    "view_mode": "form",
                    "res_id": self.mrp_production_ids.mrp_batch_id.id,
                }
            )
        else:
            # If there are multiple batches, open them in tree and form view with a
            # domain filter.
            action.update(
                {
                    "name": _(
                        "Manufacturing Production Batch Generated by %s", self.name
                    ),
                    "domain": [("id", "in", self.mrp_production_ids.mrp_batch_id.ids)],
                    "view_mode": "tree,form",
                }
            )
        return action

    # END #########
