# pylint: disable=pointless-statement
{
    "name": "OnLogic UUID",
    "summary": "Adds UUID to existing Odoo models.",
    "version": "1.0",
    "license": "AGPL-3",
    "depends": [
        "base",
        "account",
        "sale",
        "delivery",
        "product",
        "ol_base",
        "mrp",
        "ol_product",
        "ol_product_classification"
    ],
    "author": "OnLogic",
    "website": "https://www.onlogic.com",
    "onlogic": True,
    "category": "Integrations",
    "description": """Adds UUID to existing Odoo models""",
    "data": [
        "views/sale_order.xml",
        "views/res_partner.xml",
        "views/product_attribute.xml",
        "views/product_attribute_classification.xml",
        "views/product_pricelist.xml",
        "views/product_template.xml",
        "views/product_category.xml",
        "views/mrp_bom.xml",
        "views/mrp_production.xml",
        "views/account_move.xml",
    ],
    "post_init_hook": "_run_install_scripts",
}
