from . import product_attribute
from . import product_template_attribute_line
from . import product_template
from . import sale_order_line
from . import sale_order
from . import res_partner
from . import stock_picking
from . import mrp_production
from . import payment_method
from . import account_move
