{
    "name": "Onlogic Dev Module Install",
    "summary": "Module for Dev's to use to install modules via single module.",
    "description": """Module for Dev's to use to install modules via single module.""",
    "author": "Onlogic",
    "website": "https://www.onlogic.com",
    "onlogic": True,
    "category": "Hidden",
    "version": "17.0.0.1.0",
    "license": "AGPL-3",
    # Modules required to this module to work properly
    "depends": [
        # Odoo Core Modules
        "account_accountant",
        "account_consolidation",
        "approvals",
        "calendar",
        "contact",
        "crm",
        "delivery_fedex",
        "delivery_ups",
        "delivery_usps",
        "documents",
        "helpdesk",
        "hr",
        "hr_contract",
        "hr_expense",
        "hr_skills",
        "knowledge",
        "mail",
        "maintenance",
        "mrp",
        "mrp_plm",
        "planning",
        "project",
        "project_todo",
        "purchase",
        "quality_control",
        "repair",
        "room",
        "sale_management",
        "sale_subscription",
        "stock",
        "stock_barcode",
        "timesheet_grid",
        # OCA Modules
        "account_avatax_oca",
        "account_move_tier_validation",
        "auditlog",
        "base_exception",
        "base_tier_validation",
        "base_tier_validation_formula",
        "base_user_role",
        "base_user_role_company",
        "mail_debrand",
        "mrp_multi_level",
        "partner_identification",
        "partner_stage",
        "partner_tier_validation",
        "product_attrbute_set",
        "product_configurator",
        "product_configurator_mrp",
        "product_configurator_mrp_quantity",
        "product_configurator_mrp_component",
        "product_configurator_restriction_policy",
        "product_configurator_sale",
        "product_state",
        "purchase_exception",
        "purchase_request",
        "purchase_request_tier_validation",
        "purchase_tier_validation",
        "sale_automatic_workflow",
        "sale_backorder",
        "sale_blanket_order",
        "sale_exception",
        "sale_product_approval",
        "sale_product_approval_mrp",
        "sale_product_approval_purchase",
        "sale_product_approval_stock",
        "sale_tier_validation",
        "scrap_reason_code",
        # Paid Modules
        "job_cost_estimate_customer",
        "sh_product_customer_code",
        "oi_login_as",
        # OSI Modules
        "mrp_batch",
        "osi_ap_addresses",
        "osi_blanket_order_mps",
        # "osi_check_alignment", # Not in Onlogic repo yet
        # "osi_downpayment_taxes",# Not in Onlogic repo yet
        "osi_mrp_bom_sequence",
        # Onlogic Modules
        "ol_account",
        "ol_account_hot_ar",
        "ol_base",
        # "ol_credit_limit", #Not ready for ONL Testing
        "ol_crm",
        "ol_crm_estimate",
        "ol_crm_mrp_plm",
        "ol_crm_purchase_request",
        "ol_crm_sale_blanket_order",
        "ol_delivery_report",
        "ol_exception",
        "ol_job_cost_estimate_customer",
        "ol_job_cost_estimator_tier_validation",
        "ol_mrp_bom_rebuild",
        "ol_mrp_plm",
        "ol_mrp_plm_cancel",
        "ol_mrp_plm_purchase",
        "ol_mrp_plm_substate",
        "ol_mrp_plm_tier_validation",
        "ol_mrp_sale_price_rollup",
        "ol_partner_stage",
        # "ol_pim", # Being Restructured
        "ol_product_configurator",
        "ol_product_configurator_sale_template",
        "ol_product_configurator_stock",
        # "ol_product_operations_category", # New module, not in ONL repo yet
        "ol_product_pricing_review",
        "ol_product_profile",
        "ol_product_ship_multiplier",
        "ol_product_state",
        "ol_product_tariff",
        "ol_product_tooling_cost",
        "ol_purchase",
        "ol_purchase_3way_match",
        "ol_purchase_last_price_info",
        "ol_purchase_request_estimate",
        "ol_rma_supplier",
        "ol_rush_order",
        "ol_sale",
        "ol_sale_blanket_order",
        "ol_sale_cost_workup",
        "ol_sale_email",
        "ol_sale_mrp_tags",
        "ol_sale_optional_product",
        "ol_sale_stock_tags",
        "ol_sale_template",
        "ol_sale_tier_validation",
        "ol_scrap_reason_code",
        "ol_stock",
        "ol_stock_constrained_sku",
        "ol_tier_validation",
    ],
    # Data Loaded.
    "data": [],
}
