{
    "name": "OnLogic Sale customization",
    "summary": "Sale modules related customization",
    "description": """Sale modules related customization.""",
    "author": "OnLogic",
    "website": "https://www.onlogic.com",
    "onlogic": True,
    "category": "Sale",
    "version": "17.0.0.1.0",
    "license": "AGPL-3",
    # any module necessary for this one to work correctly
    "depends": [
        "ol_base",
        "ol_templates",
        "ol_product_configurator",
        "ol_exception",
        "sale_management",
        "product_state",
        "sale_subscription",
        "stock",
        "product_configurator_sale_mrp",
        "mrp_batch",
        "sale_order_type",
        "sale_exception",
        "sale_order_revision",
        "account_avatax_sale_oca",
        "ol_rush_order"
    ],
    # always loaded
    "data": [
        "security/ir.model.access.csv",
        "reports/sale_order_quote.xml",
        "data/budgetary_quote_email.xml",
        "data/crm_tag_data.xml",
        "data/product_price_list_data.xml",
        "data/product_state_data.xml",
        "data/ir_cron.xml",
        "data/sale_exception.xml",
        "data/shipping_email.xml",
        "data/invoice_created.xml",
        "data/confirmation_email.xml",
        "data/function_data.xml",
        "data/sale_order_type_data.xml",
        "data/click_to_buy_email.xml",
        "views/product_attribute_views.xml",
        "views/product_template_attribute_line_views.xml",
        "views/product_template_views.xml",
        "views/sale_order_view.xml",
        "views/res_partner_view.xml",
        "views/sale_subscription_views.xml",
        "views/stock_picking_view.xml",
        "views/mrp_production_view.xml",
        "views/payment_method_view.xml",
        "views/confirmation_email.xml",
        "views/mrp_production_batch_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/forward_confirmation_email_wizard.xml",
    ],
}
