{
    "name": "Onlogic Accounting",
    "summary": "Accounting Enhancements.",
    "description": """Accounting Enhancements.""",
    "author": "Onlogic",
    "website": "https://www.onlogic.com",
    "onlogic": True,
    "category": "Accounting",
    "version": "17.0.0.1.0",
    "license": "AGPL-3",
    # Modules required to this module to work properly
    "depends": [
        "ol_base",
        "ol_templates",
        "ol_fraud_detection",
        "account",
        "sale",
        "sale_order_type",
        "account_check_printing",
        "purchase",
        "osi_l10n_us_payment_nacha_email",
        "account_followup",
    ],
    # Data Loaded.
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/generic_invoice_email.xml",
        "data/invoice_email.xml",
        "data/mail_template_data.xml",
        "data/server_action.xml",
        "views/res_config_settings_views.xml",
        "views/account_invoice.xml",
        "views/account_payment_view.xml",
        "views/res_partner_view.xml",
        "views/payment_preference_view.xml",
        "reports/invoice_generic.xml",
        "reports/invoice_proforma.xml",
    ],
}
