from . import res_company
from . import res_config_settings
from . import stock_move_line
from . import product_supplierinfo_inherit
from . import sale_order
from . import quote
from . import mrp_skill
from . import mrp_workcenter_inherit
from . import mrp_routing_workcenter_inherit
from . import mrp_workcenter_skill
from . import mrp_secondary_workcenter
from . import mrp_workorder_secondary_workcenter
from . import mrp_workorder_inherit
from . import mrp_production_inherit
